################################################################
#                                                              #
#  This file is part of HermesBaby                             #
#                       the software engineer's typewriter     #
#                                                              #
#      https://github.com/hermesbaby                           #
#                                                              #
#  Copyright (c) 2024 Alexander Mann-Wahrenberg (basejumpa)    #
#                                                              #
#  License(s)                                                  #
#                                                              #
#  - MIT for contents used as software                         #
#  - CC BY-SA-4.0 for contents used as method or otherwise     #
#                                                              #
################################################################

import os
import pytest
from pathlib import Path


def test_pdf_command_generates_tex_files(cli_runner, project_dir):
    """Test that 'hb pdf' command generates .tex files without building PDFs."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, f"Setup failed: {result.output}"
    
    # Set environment variable to skip post-build commands
    os.environ['HERMESBABY_SKIP_POST_BUILD'] = '1'
    
    try:
        # Test the pdf command as a black box
        result = cli_runner.invoke(app, ["pdf", "."])
        
        # The command should succeed (or fail with warnings, but not crash)
        # Note: We use exit_code != 0 check because warnings may cause non-zero exit
        if result.exit_code != 0:
            # Check if it's just warnings about missing documents (acceptable)
            if "unknown document" not in result.output:
                assert result.exit_code == 0, f"PDF command failed: {result.output}"
    finally:
        # Clean up environment variable
        os.environ.pop('HERMESBABY_SKIP_POST_BUILD', None)
    
    # Verify that LaTeX files were generated in the expected location
    build_dir = project_dir / "out" / "docs" / "latex"
    tex_files = list(build_dir.glob("*.tex"))
    
    assert len(tex_files) > 0, f"No .tex files generated in {build_dir}"
    
    # Verify Makefile exists (generated by Sphinx for LaTeX builds)
    makefile = build_dir / "Makefile"
    assert makefile.exists(), f"Makefile not generated: {makefile}"


def test_pdf_command_validates_latex_content(cli_runner, project_dir):
    """Test that 'hb pdf' generates LaTeX files with expected structure."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, f"Setup failed: {result.output}"
    
    # Set environment variable to skip post-build commands
    os.environ['HERMESBABY_SKIP_POST_BUILD'] = '1'
    
    try:
        # Test the pdf command as a black box
        result = cli_runner.invoke(app, ["pdf", "."])
        
        # Handle potential warnings about missing documents
        if result.exit_code != 0 and "unknown document" not in result.output:
            assert result.exit_code == 0, f"PDF command failed: {result.output}"
    finally:
        # Clean up environment variable
        os.environ.pop('HERMESBABY_SKIP_POST_BUILD', None)
    
    # Verify that LaTeX files have expected structure
    build_dir = project_dir / "out" / "docs" / "latex"
    tex_files = list(build_dir.glob("*.tex"))
    assert len(tex_files) > 0, f"No .tex files generated"
    
    # Read one of the LaTeX files and verify it has proper structure
    main_tex_file = tex_files[0]
    tex_content = main_tex_file.read_text()
    
    # Verify LaTeX document structure
    assert "\\documentclass" in tex_content, "LaTeX document class not found"
    assert "\\begin{document}" in tex_content, "Document begin not found"
    assert "\\end{document}" in tex_content, "Document end not found"


def test_pdf_command_with_custom_config(cli_runner, project_dir):
    """Test 'hb pdf' with custom configuration."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, f"Setup failed: {result.output}"
    
    # Create custom configuration
    build_dir_name = "my-custom-build"
    config_file = project_dir / ".hermesbaby"
    with config_file.open("w") as f:
        f.write(f'CONFIG_BUILD__DIRS__BUILD="{build_dir_name}"' + os.linesep)
    
    # Set environment variable to skip post-build commands
    os.environ['HERMESBABY_SKIP_POST_BUILD'] = '1'
    
    try:
        # Test the pdf command as a black box
        result = cli_runner.invoke(app, ["pdf", "."])
        
        # Handle potential warnings
        if result.exit_code != 0 and "unknown document" not in result.output:
            assert result.exit_code == 0, f"PDF command failed: {result.output}"
    finally:
        # Clean up environment variable
        os.environ.pop('HERMESBABY_SKIP_POST_BUILD', None)
    
    # Verify LaTeX files were generated in custom directory
    expected_dir = project_dir / build_dir_name / "latex"
    tex_files = list(expected_dir.glob("*.tex"))
    assert len(tex_files) > 0, f"No .tex files generated in custom directory: {expected_dir}"


def test_pdf_command_skips_post_build(cli_runner, project_dir):
    """Test that post-build commands are skipped when environment variable is set."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, f"Setup failed: {result.output}"
    
    # Set environment variable to skip post-build commands
    os.environ['HERMESBABY_SKIP_POST_BUILD'] = '1'
    
    try:
        # Test the pdf command
        result = cli_runner.invoke(app, ["pdf", "."])
        
        # Command should succeed
        assert result.exit_code == 0, f"PDF command failed: {result.output}"
    finally:
        # Clean up environment variable
        os.environ.pop('HERMESBABY_SKIP_POST_BUILD', None)
    
    # Find where LaTeX files were actually generated (search common locations)
    possible_locations = [
        project_dir / "out" / "docs" / "latex",
        project_dir / "out" / "latex",
        project_dir / "my-custom-build" / "latex",  # In case of leftover config
    ]
    
    tex_files = []
    pdf_files = []
    actual_build_dir = None
    
    for build_dir in possible_locations:
        if build_dir.exists():
            tex_files = list(build_dir.glob("*.tex"))
            if tex_files:
                actual_build_dir = build_dir
                pdf_files = list(build_dir.glob("*.pdf"))
                break
    
    assert len(tex_files) > 0, f"LaTeX files should be generated. Checked: {possible_locations}"
    assert len(pdf_files) == 0, f"PDF files should not be generated when post-build is skipped (found in {actual_build_dir})"


def test_pdf_command_conf_py_configuration(cli_runner, project_dir):
    """Test that conf.py LaTeX configuration is properly used."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, f"Setup failed: {result.output}"
    
    # Read conf.py to verify configuration exists
    from src.hermesbaby import __main__ as main_module
    conf_path = main_module._get_resource_path('conf.py')
    
    with open(conf_path, 'r') as f:
        conf_content = f.read()
    
    # Verify latex_elements configuration exists
    assert 'latex_elements' in conf_content, "latex_elements not found in conf.py"
    assert 'papersize' in conf_content, "papersize not configured"
    assert 'latex_documents' in conf_content, "latex_documents not configured"
    
    # Verify pre_post_build_programs configuration
    assert 'pre_post_build_programs' in conf_content, "pre_post_build_programs not found"
    assert '"builder": "latex"' in conf_content, "No post-build commands for LaTeX builder"
    assert '"program": "make"' in conf_content, "make command not configured"
    assert 'Create PDF from Latex code' in conf_content, "PDF creation post-build not configured"


