################################################################
#                                                              #
#  This file is part of HermesBaby                             #
#                       the software engineer's typewriter     #
#                                                              #
#      https://github.com/hermesbaby                           #
#                                                              #
#  Copyright (c) 2024 Alexander Mann-Wahrenberg (basejumpa)    #
#                                                              #
#  License(s)                                                  #
#                                                              #
#  - MIT for contents used as software                         #
#  - CC BY-SA-4.0 for contents used as method or otherwise     #
#                                                              #
################################################################

import os
import pytest
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch, MagicMock
import importlib


def _create_mock_process():
    """Create a mock process for subprocess.Popen that simulates successful execution."""
    mock_process = MagicMock()
    mock_process.stdout = MagicMock()
    mock_process.stderr = MagicMock()
    mock_process.stdout.readline = MagicMock(return_value="")
    mock_process.stderr.readline = MagicMock(return_value="")
    mock_process.returncode = 0
    mock_process.wait = MagicMock(return_value=None)
    mock_process.poll = MagicMock(return_value=0)
    mock_process.stdout.close = MagicMock(return_value=None)
    mock_process.stderr.close = MagicMock(return_value=None)
    mock_process.communicate = MagicMock(return_value=("", ""))
    mock_process.args = []
    # Add context manager support
    mock_process.__enter__ = MagicMock(return_value=mock_process)
    mock_process.__exit__ = MagicMock(return_value=None)
    return mock_process


def test_latex_builder_generates_tex_files(cli_runner, project_dir):
    """Test that the LaTeX builder generates .tex files without building PDFs."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, "Setup failed"
    
    # Set environment variable to skip post-build commands
    os.environ['HERMESBABY_SKIP_POST_BUILD'] = '1'
    
    try:
        # Build with LaTeX builder using sphinx-build directly
        from src.hermesbaby.__main__ import _get_kconfig, _load_config, _set_env, _get_resource_path, _resolve_tool
        
        _set_env()
        _load_config()
        
        kconfig = _get_kconfig()
        build_dir = project_dir / Path(kconfig.syms["BUILD__DIRS__BUILD"].str_value) / "latex"
        source_dir = kconfig.syms["BUILD__DIRS__SOURCE"].str_value
        
        executable = _resolve_tool("sphinx-build")
        command = [
            f"{executable}",
            "-b",
            "latex",
            
            "-c",
            f"{_get_resource_path('')}",
            f"{source_dir}",
            f"{build_dir}",
        ]
        
        result = subprocess.run(command, cwd=project_dir, check=False, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"\n=== Sphinx Build Error ===")
            print(f"Return code: {result.returncode}")
            print(f"Stdout: {result.stdout}")
            print(f"Stderr: {result.stderr}")
            print("==========================\n")
        assert result.returncode == 0, f"LaTeX build failed: {result.stderr}"
    finally:
        # Clean up environment variable
        os.environ.pop('HERMESBABY_SKIP_POST_BUILD', None)
    
    # Verify that LaTeX files were generated
    tex_files = list(build_dir.glob("*.tex"))
    print(f"\n=== Generated .tex files ===")
    print(f"Found {len(tex_files)} .tex files:")
    for f in tex_files:
        print(f"  - {f.name}")
    print("============================\n")
    assert len(tex_files) > 0, f"No .tex files generated in {build_dir}"
    
    # Verify at least one main document file exists (the actual name depends on config)
    # The default template creates a PDF with title based on project name
    assert len(tex_files) > 0, f"No main LaTeX files found in {build_dir}"
    
    # Verify Makefile exists (generated by Sphinx for LaTeX builds)
    makefile = build_dir / "Makefile"
    assert makefile.exists(), f"Makefile not generated: {makefile}"


def test_latex_output_contains_expected_content(cli_runner, project_dir):
    """Test that the generated LaTeX files contain expected content."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, "Setup failed"
    
    # Patch subprocess.Popen in the pre-post-build module
    import_path = 'hermesbaby.pre-post-build'
    pre_post_build_module = importlib.import_module(import_path)
    
    with patch.object(pre_post_build_module.subprocess, 'Popen', return_value=_create_mock_process()):
        # Build with LaTeX builder
        from src.hermesbaby.__main__ import _get_kconfig, _load_config, _set_env, _get_resource_path, _resolve_tool
        
        _set_env()
        _load_config()
        
        kconfig = _get_kconfig()
        build_dir = project_dir / Path(kconfig.syms["BUILD__DIRS__BUILD"].str_value) / "latex"
        source_dir = kconfig.syms["BUILD__DIRS__SOURCE"].str_value
        
        executable = _resolve_tool("sphinx-build")
        command = [
            f"{executable}",
            "-b",
            "latex",
            
            "-c",
            f"{_get_resource_path('')}",
            f"{source_dir}",
            f"{build_dir}",
        ]
        
        subprocess.run(command, cwd=project_dir, check=True, capture_output=True, text=True)
    
    # Read the main LaTeX file
    main_tex_file = build_dir / "hermesbaby.tex"
    tex_content = main_tex_file.read_text()
    
    # Verify LaTeX document structure
    assert "\\documentclass" in tex_content, "LaTeX document class not found"
    assert "\\begin{document}" in tex_content, "Document begin not found"
    assert "\\end{document}" in tex_content, "Document end not found"
    
    # Verify Sphinx-specific LaTeX elements
    assert "\\sphinxtableofcontents" in tex_content or "\\tableofcontents" in tex_content, "Table of contents not found"


def test_latex_builder_with_custom_config(cli_runner, project_dir):
    """Test LaTeX builder with custom configuration."""
    from src.hermesbaby.__main__ import app
    
    # Create a file ".hermesbaby" with custom build directory
    build_dir = "my-custom-build"
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", ""])
    assert result.exit_code == 0, "Setup failed"
    
    config_file = project_dir / ".hermesbaby"
    with config_file.open("w") as f:
        f.write(f'CONFIG_BUILD__DIRS__BUILD="{build_dir}"' + os.linesep)
    
    # Patch subprocess.Popen in the pre-post-build module
    import_path = 'hermesbaby.pre-post-build'
    pre_post_build_module = importlib.import_module(import_path)
    
    with patch.object(pre_post_build_module.subprocess, 'Popen', return_value=_create_mock_process()):
        # Build with LaTeX builder
        from src.hermesbaby.__main__ import _get_kconfig, _load_config, _set_env, _get_resource_path, _resolve_tool
        
        _set_env()
        _load_config()
        
        kconfig = _get_kconfig()
        latex_build_dir = Path(kconfig.syms["BUILD__DIRS__BUILD"].str_value) / "latex"
        source_dir = kconfig.syms["BUILD__DIRS__SOURCE"].str_value
        
        executable = _resolve_tool("sphinx-build")
        command = [
            f"{executable}",
            "-b",
            "latex",
            
            "-c",
            f"{_get_resource_path('')}",
            f"{source_dir}",
            f"{latex_build_dir}",
        ]
        
        subprocess.run(command, cwd=project_dir, check=True, capture_output=True, text=True)
    
    # Verify LaTeX files were generated in custom directory
    expected_dir = project_dir / build_dir / "latex"
    assert expected_dir.exists(), f"Custom build directory not created: {expected_dir}"
    
    tex_files = list(expected_dir.glob("*.tex"))
    assert len(tex_files) > 0, f"No .tex files generated in custom directory: {expected_dir}"


def test_latex_builder_prevents_pdf_generation_via_mock(cli_runner, project_dir):
    """Test that mocking post-build commands prevents actual PDF generation."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, "Setup failed"
    
    # Track if post-build command was called
    post_build_calls = []
    
    def mock_popen_side_effect(*args, **kwargs):
        """Mock that records when post-build commands are called."""
        post_build_calls.append(args)
        return _create_mock_process()
    
    # Patch subprocess.Popen in the pre-post-build module
    import_path = 'hermesbaby.pre-post-build'
    pre_post_build_module = importlib.import_module(import_path)
    
    with patch.object(pre_post_build_module.subprocess, 'Popen', side_effect=mock_popen_side_effect):
        # Build with LaTeX builder
        from src.hermesbaby.__main__ import _get_kconfig, _load_config, _set_env, _get_resource_path, _resolve_tool
        
        _set_env()
        _load_config()
        
        kconfig = _get_kconfig()
        build_dir = Path(kconfig.syms["BUILD__DIRS__BUILD"].str_value) / "latex"
        source_dir = kconfig.syms["BUILD__DIRS__SOURCE"].str_value
        
        executable = _resolve_tool("sphinx-build")
        command = [
            f"{executable}",
            "-b",
            "latex",
            
            "-c",
            f"{_get_resource_path('')}",
            f"{source_dir}",
            f"{build_dir}",
        ]
        
        subprocess.run(command, cwd=project_dir, check=True, capture_output=True, text=True)
    
    # Verify post-build was called and mocked
    assert len(post_build_calls) > 0, "Post-build commands should have been called and mocked"
    
    # Verify no actual PDF files were generated
    pdf_files = list(build_dir.glob("*.pdf"))
    assert len(pdf_files) == 0, f"PDF files should not be generated when post-build is mocked"


def test_latex_makefile_structure(cli_runner, project_dir):
    """Test that the generated Makefile has the expected structure."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, "Setup failed"
    
    # Patch subprocess.Popen in the pre-post-build module
    import_path = 'hermesbaby.pre-post-build'
    pre_post_build_module = importlib.import_module(import_path)
    
    with patch.object(pre_post_build_module.subprocess, 'Popen', return_value=_create_mock_process()):
        # Build with LaTeX builder
        from src.hermesbaby.__main__ import _get_kconfig, _load_config, _set_env, _get_resource_path, _resolve_tool
        
        _set_env()
        _load_config()
        
        kconfig = _get_kconfig()
        build_dir = Path(kconfig.syms["BUILD__DIRS__BUILD"].str_value) / "latex"
        source_dir = kconfig.syms["BUILD__DIRS__SOURCE"].str_value
        
        executable = _resolve_tool("sphinx-build")
        command = [
            f"{executable}",
            "-b",
            "latex",
            
            "-c",
            f"{_get_resource_path('')}",
            f"{source_dir}",
            f"{build_dir}",
        ]
        
        subprocess.run(command, cwd=project_dir, check=True, capture_output=True, text=True)
    
    # Read and verify Makefile
    makefile = build_dir / "Makefile"
    makefile_content = makefile.read_text()
    
    # Verify Makefile contains expected targets
    assert "all:" in makefile_content or "all-pdf:" in makefile_content, "Makefile missing 'all' target"
    assert "pdflatex" in makefile_content.lower() or "latexmk" in makefile_content.lower(), "Makefile missing LaTeX compilation command"


def test_latex_builder_conf_py_configuration(cli_runner, project_dir):
    """Test that conf.py LaTeX configuration is properly loaded."""
    from src.hermesbaby.__main__ import app
    
    # Run the "new" command to set up the project
    result = cli_runner.invoke(app, ["new", "."])
    assert result.exit_code == 0, "Setup failed"
    
    # Read conf.py directly to verify configuration
    from src.hermesbaby import __main__ as main_module
    conf_path = main_module._get_resource_path('conf.py')
    
    # Read the conf.py file content
    with open(conf_path, 'r') as f:
        conf_content = f.read()
    
    # Verify latex_elements configuration exists
    assert 'latex_elements' in conf_content, "latex_elements not found in conf.py"
    assert 'papersize' in conf_content, "papersize not configured in latex_elements"
    assert 'pointsize' in conf_content, "pointsize not configured in latex_elements"
    assert 'preamble' in conf_content, "preamble not configured in latex_elements"
    
    # Verify latex_documents configuration
    assert 'latex_documents' in conf_content, "latex_documents not found in conf.py"
    
    # Verify pre_post_build_programs configuration
    assert 'pre_post_build_programs' in conf_content, "pre_post_build_programs not found in conf.py"
    
    # Verify LaTeX-specific post-build commands exist
    assert '"builder": "latex"' in conf_content, "No post-build commands configured for LaTeX builder"
    
    # Verify the make command is configured for PDF generation
    assert '"program": "make"' in conf_content, "make command not configured for LaTeX post-build"
    assert 'Create PDF from Latex code' in conf_content, "PDF creation post-build not configured"

