name: docs -> build

on:
    push:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
  contents: read

jobs:
  docs_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install hermesbaby
        run: python -m pipx install hermesbaby

      - name: Install tools
        run: hb tools install

      - name: Build docs
        run: hb html

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out/docs/html'

