name: docs -> build and publish

on:
    push:
        tags:
            - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs_build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install hermesbaby
        run: python -m pip install hermesbaby

      - name: Install tools
        run: hb tools install

      - name: Build main website
        run: hb html

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out/docs/html'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish website at GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
