name: Test, Build and Package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install pipx
        pipx install poetry
        pipx runpip poetry install poetry-dynamic-versioning

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Build package
      run: |
        poetry run pyinstaller hermesbaby.spec

    - name: Smoke Test executable
      run: |
        cd dist/hermesbaby
        ./hb.exe
        ./hb.exe --help
        ./hb.exe --version
        ./hb.exe new --list-templates
        ./hb.exe new --template zero test01
        cd test01
        ../hb.exe html
      shell: cmd

    - name: Install WiX v4
      run: |
        curl -L -o wix.zip https://github.com/wixtoolset/wix/releases/download/v4.0.4/wix-4.0.4.zip
        Expand-Archive wix.zip -DestinationPath $Env:ProgramFiles\wix
        echo "$Env:ProgramFiles\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Create MSI installer
      run: |
        $AppDir = "C:\data\d\github\hermesbaby\hermesbaby\dist\hermesbaby"
        $env:PRODUCT_VERSION = "25.10.03.41"
        wix build `
        -arch x64 `
        -bindpath app="$AppDir" `
        -define ProductVersion=$env:PRODUCT_VERSION `
        -out ".\dist\HermesBaby-$env:PRODUCT_VERSION-x64.msi" `
        "Package.wxs"
      shell: pwsh
