name: Test, Build, Package and Publish

on:
    push:
        tags:
            - 'v*'
    branches:
      - main

jobs:
  test_build_package_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Install Poetry
      run: |
        pip install pipx
        pipx install poetry

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Install external tools
      run: |
        sudo ./src/hermesbaby/setup.sh

    - name: Run tests
      run: |
        poetry run pytest

    - name: Build package
      run: |
        poetry build

    - name: Publish to PyPI
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --username user: $PYPI_USERNAME --password $PYPI_PASSWORD
